### ISSUE TITLE
enabling multiple selection

### ISSUE THREAD

**Issue by larryhengl** [zippyui/react-datagrid#30]
Hi Folks,  nice lib.  
Trying to get the multi-selection working.  What I'm seeing on row click and shift+click is the idProperty value for the selected row, and not an object of selected rows like I see in the demo.  Should I do anything specific to enable this?

I simply did an npm install to get the latest version, then required it into my component. 
Also placing the SELECTED_ID tracking in my component state (as opposed to the scoped vars in the demo) - this works fine for single row selection.
When inspecting my onSelectionChange handler I only see a value passed in, not an object.
Any ideas?

Cheers,
:Larry

**Comment by zippyui-react** [comment]
Hi Larry,

we're glad you like our component. In order to get multiple selection working, you have to pass in an object into the `selected` (controlled behaviour) or the `defaultSelected` prop (uncontrolled). This object should have keys being the ids of your selected objects. If you only pass in a string/number, single selection will be assumed.

For multiple selection, the `onSelectionChange` handler will be called upon selection change, with 2 args, first the new map of selected ids, and second the array of selected objects.

**Comment by larryhengl** [comment]
Thanks for the explanation, got it working.  Closing issue.  And thanks again for sharing this project!
:L

**Comment by zippyui-react** [comment]
We're glad to help!
