### ISSUE TITLE
Refreshing

### ISSUE THREAD

**Issue by danielearwicker** [zippyui/react-datagrid#4]
The examples pass an empty object in to trick react into re-rendering:

    this.setState({})

Why is it done that way? Shouldn't the updated information be passed in via state or props? It seems to go against the design of React.

**Comment by zippyui-react** [comment]
Thanks for the question Daniel.

We implemented it like this since we wanted to keep things as stateless as possible. See https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#what-components-should-have-state. So we followed the recommandation to 
> Try to keep as many of your components as possible stateless.

This is conforming to the design of React, not against it. Since the examples are exporting an React class, and we do not have direct access to the mount node and the top-level component, so we could do `topCmp.setProps`, we chose to do a `setState` to trigger a refresh.

The idea is to have a **single sorce of truth** in your React apps, which we are having. And just as you said, the updated information is passed in as props (to the DataGrid). We first update the source of truth and then re-render everything. Notice we go with the React design, since we keep things as stateless as possible. You can think of the local vars that are  passed in as props to the DataGrid, in a real app, as being an object (maybe sent as JSON from the server) stored as app state.

What are your thoughts?

**Comment by danielearwicker** [comment]
I see - in the example I looked at, a `data` array is being passed down to the grid in props, so in fact the `setState` call is only on the example component. Your grid itself is "well behaved" in that it is just rendering based on props.

I suspect that it would be clearer if such an example used `setState` to store things like the `data` array. As it is, the component is still stateful - the state is stored in variables outside, but that's still mutable state.

**Comment by zippyui-react** [comment]
Well, I wouldn't call it stateful. You need to render your React app from a data source (the source of truth) - the app is a function of the props passed in. So generally you have a nested object (that is the app state) and you pass that to the top-level component so your app gets rendered.

It's true in the examples we don't pass the props to the top-level App cmp, but to the datagrid - but this is done since in the examples you don't have access to how the top level cmp is rendered (under the hood it is rendered as <App />), so therefore, you can consider the child of the app cmp as the top-level cmp in our examples.

Stateful components are components that hold state internally.

**Comment by arrb** [comment]
I have a promise on DataSource, when I sort the table, I call setState({}) and it re renders; however, the data does not get updated unless I change the pageSize
