### ISSUE TITLE
Need a setting to allow dynamic row height

### ISSUE THREAD

**Issue by longd3** [zippyui/react-datagrid#49]
When each cell data is lengthy and user wishes to see everything, i.e. overflow-scroll-y: auto; I wonder if there has been a setting for rowHeight to allow such behavior. Otherwise, I appreciate if you consider adding it to future features.

**Comment by algm** [comment]
What it would be really cool imho is that the cell expanded and floated in order to wrap its content, that would make data visualization much more powerful. Anyway, I think It would be possible to do that in the current version by using the column renderer functions to render the data in a React component that does just that.

**Comment by zippyui-react** [comment]
Yep, using the `column.render` function is the  nice way to accomplish just that, without adding extra features to the grid.
Anyway, you have `rowHeight` prop available, which is a controlled prop. So on cell click, you can update the rowHeight. But that would update rowHeight for all rows, so this is probably not what you want.
I would go by using a custom render function.
